export const DATA_ACTIONS = {
  FETCH_POSTS: "FETCH_POSTS",
  FETCH_POSTS_START: "FETCH_POSTS_START",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_ERROR: "FETCH_POSTS_ERROR",

  ADD_POST: "ADD_POST",

}